#pragma once

#include <projects/M_GStream/renderer/Config.hpp>

#ifdef SIBR_OS_WINDOWS
#ifndef SIBR_EXTENDED_GAUSSIAN_SERVER_EXPORT
#if defined(SIBR_EXTENDED_GAUSSIAN_SERVER_STATIC_DEFINE)
#define SIBR_EXTENDED_GAUSSIAN_SERVER_EXPORT
#elif defined(SIBR_EXTENDED_GAUSSIAN_SERVER_EXPORTS)
#define SIBR_EXTENDED_GAUSSIAN_SERVER_EXPORT __declspec(dllexport)
#else
#define SIBR_EXTENDED_GAUSSIAN_SERVER_EXPORT __declspec(dllimport)
#endif
#endif
#ifndef SIBR_EXTENDED_GAUSSIAN_SERVER_NO_EXPORT
#define SIBR_EXTENDED_GAUSSIAN_SERVER_NO_EXPORT
#endif
#else
#define SIBR_EXTENDED_GAUSSIAN_SERVER_EXPORT
#define SIBR_EXTENDED_GAUSSIAN_SERVER_NO_EXPORT
#endif
